### ISSUE TITLE
facilitate self signed ssl

### ISSUE THREAD

**Issue by mimizone** [ekristen/docker-index-cli#5]
would there be a way to by default force --insecure and the index URI to avoid having to type it over and over?

**Comment by ekristen** [comment]
Try this branch real quick. 
1. `npm install -g git://github.com/ekristen/docker-index-cli.git#rc`
2. Create a config file in one of the following locations https://www.npmjs.com/package/rc#standards
```json
{
  "insecure": true
}
```

**Comment by mimizone** [comment]
thanks.
worked with the info in /etc/docker-index-clirc

could we stuff also the default index URI in there also?

**Comment by ekristen** [comment]
It might be possible. However since the `docker` cli tool requires the hostname whenever working with images not on the main public registry, this tool works the same way to keep the pattern of interaction the same.

**Comment by mimizone** [comment]
what do you think of instead of true/false, having a list of URI would be more useful.
something like the following:
```json
{
  "secure":{
    "index1.private.io",
    "index2.private.io" 
  }
}
```

the DOCKER_OPTS variable allows to have multiple insecure URI.

**Comment by ekristen** [comment]
Are you actually running multiple indexes and if so may I ask why?

**Comment by mimizone** [comment]
I am not. Maybe it doesn't make much sense.

**Comment by ekristen** [comment]
Docker registry v1 is about to be deprecated entirely from the docker engine, this project will soon be deprecated as well.
