### ISSUE TITLE
docker already login successded but can not listUsers

### ISSUE THREAD

**Issue by lioncui** [ekristen/docker-index-cli#8]
[root@docker ~]# docker login 127.0.0.1:5100
Username (admin): admin
WARNING: login credentials saved in /root/.docker/config.json
Login Succeeded
[root@docker ~]# docker-index listUsers
First use docker login to authenticate to your registry/index

**Comment by ekristen** [comment]
There is a bug in the `docker-index listUsers` feature. I have not had time to find and fix.
